### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by shzxm** [qsbaq/vps-stock-monitor#1]
Django Version: | 3.0.7
-- | --
TypeError
'NoneType' object is not subscriptable
/root/vps-stock-monitor/vps/views.py in index, line 31
/usr/bin/python3
3.8.2
['/root/vps-stock-monitor',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages']

**Comment by qsbaq** [comment]
> 
> Django Version: 	3.0.7
> TypeError 	
> 'NoneType' object is not subscriptable 	
> /root/vps-stock-monitor/vps/views.py in index, line 31 	
> /usr/bin/python3 	
> 3.8.2 	
> ['/root/vps-stock-monitor', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

已添加无数据检测，请更新版本。
